package com.example.hello_selenium_junit;

// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void searchdevops() {
        driver.get("https://www.google.com/");
        driver.switchTo().frame(0);
        WebElement we = new WebDriverWait(driver, 10)
                .until(ExpectedConditions.elementToBeClickable(By.id("introAgreeButton")));
        we.click();
        driver.switchTo().defaultContent();
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("devops");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        we = new WebDriverWait(driver, 10)
                .until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(.,\'DevOps - Wikipedia, la enciclopedia libre\')]")));
        we.click();
        //driver.findElement(By.xpath("//span[contains(.,\'DevOps - Wikipedia, la enciclopedia libre\')]")).click();
    }
}